### ISSUE TITLE
Backport to 1.20.6

### ISSUE THREAD

**Issue by Blutoppia** [DimasKama/OrthoCamera#11]
Hi,
I just wanted to say that I love your work and that the OrthoCamera looks awsome to use.
And i'd love to use but I see that there is no version for 1.20.6. I am not very good coding and mods and everything so i wanted to ask if maybe you could make a version for 1.20.6.

It would mean alot.

Sincerly,

**Comment by DimasKama** [comment]
Hi,
The version for mc 1.20.5 also works for 1.20.6. It`s available on modrinth: https://modrinth.com/mod/orthocamera/version/0.1.7+1.20.5

**Comment by Blutoppia** [comment]
Thank You! Just 1 more thing... 
As I mentioned before I am not the best with modding and stuff
Does this mean basically any 1.20.5 mod is usable in 1.20.6 
And are 1.20.4 mods also usable

I hope i haven't disturbed you much with my questions

Kind regards,

**Comment by DimasKama** [comment]
1.20.6 was a minor hotfix-update: https://minecraft.wiki/w/Java_Edition_1.20.6. So the most mods for 1.20.5 also work on 1.20.6.

But 1.20.5 was a big update with a lot of technical changes: https://minecraft.wiki/w/Java_Edition_1.20.5. Most mods for 1.20.4 will not work on 1.20.5.
