### ISSUE TITLE
Incompatible with Sodium

### ISSUE THREAD

**Issue by Wolfik-Morgan** [DimasKama/OrthoCamera#12]
I installed the mod just to find some blocks one sided when the camera was turned on, upon testing i found out the issue was with Sodium which specializes in optimization and most likely disables block rendering if they arent directly seen, issue is it doesnt register the Ortho camera as a player meaning it doesnt render the blocks to save up FPS
![see trough](https://github.com/user-attachments/assets/c527e158-cd27-4926-9571-9b63288373c7)

**Comment by DimasKama** [comment]
Please, read the README.txt on GitHub or mod description on ModRinth

**Comment by Wolfik-Morgan** [comment]
> Please, read the README.txt on GitHub or mod description on ModRinth

my bad, it kinda sucks that the part mentioning that is in a read me file but thanks otherwise.

**Comment by Wolfik-Morgan** [comment]
> Please, read the README.txt on GitHub or mod description on ModRinth

Actually an another issue i am having right now is the fact i can for some reason see my hand in the camera and cant see the player model

**Comment by DimasKama** [comment]
You can change the perspective by F5. Nothing else will change, but the hand disappears and the player becomes visible
