### ISSUE TITLE
Seeing through blocks

### ISSUE THREAD

**Issue by Frostyy1217** [DimasKama/OrthoCamera#15]
Hello whenever i try and use the mod, it never fully loads and many blocks end up being invis
![2024-08-20_14 36 39](https://github.com/user-attachments/assets/4cdf402e-cf04-4f4b-9db0-d2eb6e49164a)
ible.

**Comment by DimasKama** [comment]
You are probably use Sodium and/or Nvidium mod. Read the README on GitHub or description on ModRinth
