### ISSUE TITLE
Add default keybinds to readme

### ISSUE THREAD

**Issue by noahbald** [DimasKama/OrthoCamera#20]
Idk what the default keybinds are or how to change them, but from [this file](https://github.com/DimasKama/OrthoCamera/blob/d356755d1369b80c64a8e1bc6a7ee20924cd0aad/src/main/java/com/dimaskama/orthocamera/client/OrthoCamera.java#L22C82-L22C95) I've been able to figure out

- Keypad 4: Toggle
- Keypad Subtract: Increase scale
- Keypad Plus: Decrease scale
- Keypad Multiply: Toggle fixed camera

**Comment by DimasKama** [comment]
Why not look at them in the control settings?

**Comment by noahbald** [comment]
Oh didn't realize it'd be there -- sorry haven't used the game in a while
