### ISSUE TITLE
Transparency layer on the skin is not displayed correctly

### ISSUE THREAD

**Issue by Xleby4ek** [DimasKama/OrthoCamera#4]
When orthographic view mode is enabled, the transparent layer starts to be displayed incorrectly, although this did not happen in previous versions of the mod
![2024-02-15_19 59 47](https://github.com/DimasKama/OrthoCamera/assets/113757538/d39a21e9-62be-4724-8b83-6d21547e6f9c)

**Comment by DimasKama** [comment]
Fixed in 0.1.2 version of the mod. Thank you!
