### ISSUE TITLE
[Bug] Slider/Button fighting in GUI Scale 4.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [DimasKama/OrthoCamera#7]
Hello!

I found that last Sliders and Buttons under them are conflicting in GUI Scale 4.

There's Screenshot:
![image](https://github.com/DimasKama/OrthoCamera/assets/51203385/befdf5f2-af76-47ec-bb9c-2bb888b04788)

**Comment by DimasKama** [comment]
Fixed in 0.1.6

**Comment by DimasKama** [comment]
Okay, I saw it still appears sometimes. Will be fixed in 0.1.7

**Comment by DimasKama** [comment]
Fixed in 0.1.7
