### ISSUE TITLE
[Feature Suggestion] Toggle/Rotate Commands

### ISSUE THREAD

**Issue by TheVisionaryOne** [DimasKama/OrthoCamera#9]
Hey! Just discovered OrthoCamera and it is SUPER cool! This mod is revolutionary, and I can honestly see it having countless use cases, especially when it comes to designing custom gamemodes and adventure maps inside Minecraft. Top-down or side-scroller camera angles are nearly effortless to set up with OrthoCamera, and they look fantastic!

However, as far as I can tell, the only way to activate/adjust OrthoCamera currently is through the use of keybinds. I'm not sure how easy this would be to implement, but I'd love to see a set of commands for toggling/rotating/configuring OrthoCamera. The addition of commands would allow the camera to be controlled by command blocks and/or datapacks, instead of being exclusive to keybinds. I truly believe this would open up a world of possibilities for mapmakers, and would love to see it implemented if you have the time!

**Comment by DimasKama** [comment]
Hello! Currently, OrthoCamera is a small, utility, fully client-side mod; it does not interact in any way with the server part of the game. So the commands that I can add will also be client commands. Datapacks and command blocks execute commands on the server, so client commands are not available to them and adding commands would not be useful.
Control of the FOV and camera rests entirely with the player and, to be honest, I don't want to change that in the main mod. Perhaps someone would like to write an addon or fork that would add the ability to control an orthographic camera. I unfortunately don't have time for this at the moment, but the mod is open for contributions, so you're welcome.
